name: PR-check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build app
        run: xcodebuild -project YandexMusic.xcodeproj -config Debug -scheme YandexMusic build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
